# See http://dev.bukkit.org/server-mods/clicksort/pages/configuration
autosave_seconds: 300
log_level: INFO
drop_excess: true
default_group_name: '000-default'
use_essentials_worth: true
coloured_console: true
defaults:
  click_mode: MIDDLE
  sort_mode: ID
  shift_click: true
