name: ClickSort
main: me.desht.clicksort.ClickSortPlugin
author: desht
version: ${project.version}
description: Super-convenient inventory sorting
website: http://dev.bukkit.org/server-mods/clicksort
softdepend: [ Essentials ]

commands:
  clicksort:
    description: Manage the ClickSort plugin
    usage: |
      /<command> reload

permissions:
  clicksort.admin:
    description: Full admin control for ClickSort
    default: op
    children:
      clicksort.commands.reload: true
  clicksort.commands.reload:
    description: Allow use of the /clicksort reload command
    default: op
  clicksort.commands.sortmode:
    description: Allow use of the /clicksort sortmode command
    default: true
  clicksort.commands.clickmode:
    description: Allow use of the /clicksort clickmode command
    default: true
  clicksort.commands.shiftclick:
    description: Allow use of the /clicksort shiftclick command
    default: true
  clicksort.sort:
    description: Allow inventory to be click-sorted
    default: true
