# See https://dev.bukkit.org/projects/clicksort/pages/configuration
autosave_seconds: 300
debug_level: 0
drop_excess: true
default_group_name: '000-default'
use_essentials_worth: true
coloured_console: true
defaults:
  click_mode: MIDDLE
  sort_mode: NAME
  shift_click: true
player_sort_min: 9
player_sort_max: 36
sortable_inventories:
  - "PLAYER"
  - "CHEST"
  - "ENDER_CHEST"
  - "SHULKER_BOX"
  - "BARREL"
